commited base code
applibgroup/TypedPreferences pull request #1
Opened 2021-11-23 09:40 UTC by Rahul1656

2021-11-24 03:41 UTC, samuel-abhishek commented on .gitignore
> +/.idea/assetWizardSettings.xml
remove .idea folder & its subfolders

2021-11-24 03:43 UTC, samuel-abhishek commented on .idea/checkstyle-idea.xml
> +  <component name="CheckStyle-IDEA">
.idea folder is folder with config files local to your IDE.  Should not be committed.

2021-11-24 03:46 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/BasePreference.java
> +/*
This is a ported library file. Copyright should not be added.

2021-11-24 03:46 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/BooleanPreference.java
> +/*
This is a ported library file. Copyright should not be added.

2021-11-24 03:46 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/DoublePreference.java
> +/*
This is a ported library file. Copyright should not be added.

2021-11-24 03:47 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/FloatPreference.java
> +/*
This is a ported library file. Copyright should not be added.

2021-11-24 03:49 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/DoublePreference.java
> +     * @param defaultValue defaultval.
incorrect java doc format. Please check and correct.

2021-11-24 03:52 UTC, samuel-abhishek commented on Library/src/main/java/info/metadude/android/typedpreferences/BooleanPreference.java
> +     * BooleanPreference.
Retain the base library's java doc comments for all the methods as its more meaningful. Applies to all the methods.

2021-11-24 03:56 UTC, samuel-abhishek commented on README.md
> +Inspired by https://github.com/johnjohndoe/TypedPreferences - version 1.0
Followthe ReadMe template shared.

2021-11-24 03:57 UTC, samuel-abhishek commented on README.md
> +Inspired by https://github.com/johnjohndoe/TypedPreferences - version 1.0
Why referring to v1.0, why not the latest v2.1.0 version of this library ? Check this

2021-11-24 03:59 UTC, samuel-abhishek commented on README.md
> +    implementation project(path: ':library')
Current lib name will cause an issue in Maven release. Refactor the lib module name from "Library" to "typedpreferences" in the project. Do the necessary changes throughout the project.

2021-11-24 04:00 UTC, samuel-abhishek commented on README.md
> +<?xml version="1.0" encoding="utf-8"?>
This is generic code not relevant to the typedPreferences library. Add the correct code snippet.

2021-11-24 04:01 UTC, samuel-abhishek commented on README.md
> +        super.setUIContent(ResourceTable.Layout_ability_main);
Irrelevant code..!! Add proper code snippet.

2021-11-24 04:04 UTC, samuel-abhishek commented on entry/src/main/java/info/metadude/android/typedpreferences/demo/PreferenceHelper.java
> +/*
Remove the applibgroup copyright from this file, as it same as base lib

2021-11-24 04:05 UTC, samuel-abhishek commented on entry/src/main/java/info/metadude/android/typedpreferences/demo/slice/MainAbilitySlice.java
> +    Text text;
Add relevant access modifier for the field members

2021-11-24 04:05 UTC, samuel-abhishek commented on entry/src/main/java/info/metadude/android/typedpreferences/demo/slice/MainAbilitySlice.java
> +     *
Incorrect java doc format.

2021-11-24 04:06 UTC, samuel-abhishek commented on entry/src/ohosTest/java/info/metadude/android/typedpreferences/demo/BooleanPrefTest.java
> +
Remove unnecessary whitelines/whitespaces. Recurrent in multiple places. Check and handle throughout the project.

2021-11-24 04:07 UTC, samuel-abhishek commented on entry/src/ohosTest/java/info/metadude/android/typedpreferences/demo/DoublePrefTest.java
> +    private DoublePreference mpreference2;
private variables must be placed below the private static variables.

2021-11-24 04:09 UTC, samuel-abhishek commented on entry/src/ohosTest/java/info/metadude/android/typedpreferences/demo/DoublePrefTest.java
> +        Preferences preferences;
Variables - preferences, databaseHelper, context;

declaration and initialization can be done in a single line.

2021-11-24 04:14 UTC, samuel-abhishek commented on README.md
Add a gif and explain the demo in gif wrt to the library.

2021-11-24 04:14 UTC, samuel-abhishek requested changes
Please check the comments and handle the changes

2021-11-29 07:50 UTC, samuel-abhishek commented on README.md
>      testImplementation 'junit:junit:4.13'
All the dependencies must be present within thin the dependency node. Please correct this

2021-11-29 07:51 UTC, samuel-abhishek commented on README.md
> +<img src="Screenshot/ezgif.com-gif-maker.gif" width="500">
as discussed previously, please show a config change in the gif, to show the actual usefulness of the functionality of this library.

2021-11-29 07:56 UTC, samuel-abhishek commented on README.md
>  2. For using apprater in separate application using har file, add the har file in the entry/libs folder and add the dependencies in entry/build.gradle file.
Replace apprater with the library name. Same issue found in multiple places..Please check

2021-11-29 08:01 UTC, samuel-abhishek commented on typedpreferences/src/main/java/info/metadude/android/typedpreferences/BooleanPreference.java
>       * Boolean.
Check the base lib's java doc method description and retain it..The previous review comment is not handled in all the places...Please check and handle in all the scenarios applicable

2021-11-29 08:17 UTC, samuel-abhishek requested changes
Please check and handle the review comments

2021-11-30 14:49 UTC, samuel-abhishek approved these changes
okay

2021-12-01 17:23 UTC, samuel-abhishek commented
Test this library on SDK6 and update the PR.

2021-12-03 05:30 UTC, samuel-abhishek approved these changes
Okay

2021-12-06 06:09 UTC, sharathks84 approved these changes
Okay Approved

2021-12-06 06:29 UTC, Gleelakrishna approved these changes
OK

2021-12-06 10:18 UTC, merged